#
# continuous integration workflow
#

name: alert app

on:
  push:
    branches: [ master]
 workflow_dispatch:
    branches: [ master]

jobs:
  trigger-package-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: trigger rebuild of package
        run: |
          curl -X POST 'https://api.github.com/repos/berndpfrommer/rebuild_app/actions/workflows/rebuild_package.yaml/dispatches' \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: Bearer ${{ secrets.PAT_BGP }}' \
          -d '{"ref":"master"}'